name: Build Container & Push to a Registry
on:
  push:
    branches:
      - main
jobs:
  # Build the container
  build-container:
    name: Build Container
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ secrets.REGISTRY_HOST }}/${{ secrets.REGISTRY_REPO }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=sha,prefix=,suffix=,format=short
          type=sha,prefix=,suffix=,format=long
          type=raw,value=latest

    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: "${{ secrets.REGISTRY_HOST }}"
        username: "${{ secrets.REGISTRY_USERNAME }}"
        password: "${{ secrets.REGISTRY_TOKEN }}"

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        file: ./Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  # Compress the container image from the registry with buildah
  buildah-package:
    name: Package Container with Buildah
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: build-container
    steps:
      - name: Install buildah
        run: |
          sudo apt-get update -qq
          sudo apt-get -qq -y install buildah
          buildah version

      - name: Make the tar with buildah
        run: |
          CONTNR=$(buildah from registry.access.redhat.com/ubi9/ubi-init:9.0.0-16)
          echo "CONTNR: $CONTNR"
          MNTPNT=$(buildah mount $CONTNR)
          echo "MNTPNT: $MNTPNT"
          cd $MNTPNT
          tar -cvf /tmp/wsl-distro.tar .

      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          path: /tmp/wsl-distro.tar
          name: wsl-distro.tar